:name: NewName
:botlet_paths: ~/custom_path/
:connectors:
  - :name: Irc
    :path: irc.rb
    :opts:
      :host: chat.freenode.net
      :port: 6667
      :channels:
        - '#channel1'
        - '#channel2'
  - :name: Http
    :path: http.rb
    :opts:
      :ip: 0.0.0.0
      :port: 8080